[package]
name = "rust-fah-pauser"
version = "0.1.0"
authors = ["Makoto <makoto@emurasoft.com>"]
edition = "2018"

[[bin]]
name = "fah-pauser"
path = "src/main.rs"

[dependencies]
lazy_static = "1.4"
error-chain = "0.12"
fahapi = "0.1"
dirs = "3.0.0"
serde = "1.0"
serde_yaml = "0.8"
